// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhXLt-wCd9ozR5lK1K7mvBnIYwuipnry4',
    appId: '1:899539362961:android:d5ed1c9513bd14da678b30',
    messagingSenderId: '899539362961',
    projectId: 'clean-catalogue-app-b0ca5',
    storageBucket: 'clean-catalogue-app-b0ca5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUeax_LHp_EIQWOdLYMfNVkYEIYKkZRC8',
    appId: '1:899539362961:ios:e241b69306d2fcc7678b30',
    messagingSenderId: '899539362961',
    projectId: 'clean-catalogue-app-b0ca5',
    storageBucket: 'clean-catalogue-app-b0ca5.appspot.com',
    androidClientId: '899539362961-2k37hptb71bv70163i20b3pomjl8uqo7.apps.googleusercontent.com',
    iosClientId: '899539362961-ndn4q8ink826hl842mrh8guduneao16t.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanCatalogueApp',
  );
}
